# Generated by Django 5.0.4 on 2024-07-05 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=550)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
