# Generated by Django 5.0.4 on 2024-07-05 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisation',
            old_name='id',
            new_name='orgId',
        ),
    ]
